from MasterEquipment import TradeGoods

tradeGoodList = []

#__init__(self, inCategory, inCost, inWeight, inGoods)
tradeGoodList.append(TradeGoods.TradeGoods("Wheat", "1 cp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Flour", "2 cp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Chicken", "2 cp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Salt", "5 cp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Iron", "1 sp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Canvas", "1 sp", "", "1 sq. yd."))
tradeGoodList.append(TradeGoods.TradeGoods("Copper", "5 sp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Cotton Cloth", "5 sp", "", "1 sq. yd."))
tradeGoodList.append(TradeGoods.TradeGoods("Ginger", "1 gp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Goat", "1 gp", "", "Full"))
tradeGoodList.append(TradeGoods.TradeGoods("Cinnamon", "2 gp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Pepper", "2 gp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Sheep", "2 gp", "", "Full"))
tradeGoodList.append(TradeGoods.TradeGoods("Cloves", "3 gp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Pig", "3 gp", "", "Full"))
tradeGoodList.append(TradeGoods.TradeGoods("Silver", "5 gp", "", "1 sq. yd."))
tradeGoodList.append(TradeGoods.TradeGoods("Linen", "5 gp", "", "1 sq. yd."))
tradeGoodList.append(TradeGoods.TradeGoods("Silk", "10 gp", "", "1 sq. yd."))
tradeGoodList.append(TradeGoods.TradeGoods("Cow", "10 gp", "", "Full"))
tradeGoodList.append(TradeGoods.TradeGoods("Saffron", "15 gp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Ox", "15 gp", "", "Full"))
tradeGoodList.append(TradeGoods.TradeGoods("Gold", "50 gp", "1 lb", ""))
tradeGoodList.append(TradeGoods.TradeGoods("Platinum", "500 gp", "1 lb", ""))
