from MasterEquipment import AdventuringGear

# __init__(self, inCategory, inName, inCost, inWeight):
adventuringGear = []
adventuringGear.append(AdventuringGear.AdventuringGear("", "Abacus", "2 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Acid (vial)", "25 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Alchemist's fire (flask)", "50 gp", "1 lb."))

# Ammunition
adventuringGear.append(AdventuringGear.AdventuringGear("Ammunition", "Arrows (20)", "1 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Ammunition", "Blowgun needles (50)", "1 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Ammunition", "Crossbow bolts (20)", "1 gp", "1.5 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Ammunition", "Sling bullets (20)", "4 cp", "1.5 lb."))

adventuringGear.append(AdventuringGear.AdventuringGear("", "Antitoxin (vial)", "50 gp", ""))

# Arcane focus
adventuringGear.append(AdventuringGear.AdventuringGear("Arcane focus", "Crystal", "10 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Arcane focus", "Orb", "20 gp", "3 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Arcane focus", "Rod", "10 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Arcane focus", "Staff", "5 gp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Arcane focus", "Wand", "10 gp", "1 lb."))

adventuringGear.append(AdventuringGear.AdventuringGear("", "Backpack", "2 gp", "5 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Ball bearings (bag of 1,000)", "1 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Barrel", "2 gp", "70 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Basket", "4 sp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Bedroll", "1 gp", "7 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Bell", "1 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Blanket", "5 sp", "3 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Block and tackle", "1 gp", "5 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Book", "25 gp", "5 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Bottle, glass", "2 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Bucket", "5 cp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Caltrops (bag of 20)", "1 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Candle", "1 cp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Case crossbow bolt", "1 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Case, map or scroll", "1 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Chain (10 feet)", "5 gp", "10 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Chalk (1 piece)", "1 cp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Chest", "5 gp", "25 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Climber's kit", "25 gp", "12 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Clothes, common", "5 sp", "3 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Clothes, costume", "5 gp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Clothes, fine", "15 sp", "6 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Clothes, traveler's", "2 gp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Component pouch", "25 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Crowbar, common", "2 gp", "5 lb."))

# Druidic focus
adventuringGear.append(AdventuringGear.AdventuringGear("Druidic focus", "Sprig of mistletoe", "1 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("Druidic focus", "Totem", "1 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("Druidic focus", "Wooden staff", "5 gp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Druidic focus", "Yew wand", "10 gp", "1 lb."))

adventuringGear.append(AdventuringGear.AdventuringGear("", "Fishing tackle", "1 gp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Flask or tankard", "2 cp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Grappling hook", "2 gp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Hammer", "1 gp", "3 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Hammer, sledge", "2 gp", "10 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Healer's kit", "5 gp", "3 lb."))

# Second half of page
adventuringGear.append(AdventuringGear.AdventuringGear("Holy symbol", "Amulet", "5 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("Holy symbol", "Emblem", "5 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("Holy symbol", "Reliquary", "5 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Holy water (flask)", "25 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Hourglass", "25 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Hunting trap", "5 gp", "25 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Ink (1 ounce bottle)", "10 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Ink pen", "2 cp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Jug or pitcher", "2 cp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Ladder (10-foot)", "1 sp", "25 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Lamp", "5 sp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Lantern, bullseye", "10 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Lantern, hooded", "5 gp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Lock", "10 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Magnifying glass", "100 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Manacles", "2 gp", "6 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Mess kit", "2 sp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Mirror, steel", "5 gp", "1/2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Oil (flask)", "1 sp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Paper (one sheet)", "2 sp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Parchment (one sheet)", "1 sp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Perfume (vial)", "5 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Pick, miner's", "2 gp", "10 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Piton", "5 cp", "1/4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Poison, basic (vial)", "100 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Pole (10-foot)", "5 cp", "7 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Pot, iron", "2 gp", "10 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Potion of healing", "50 gp", "1/2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Pouch", "5 sp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Quiver", "1 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Ram, portable", "4 gp", "35 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Rations (1 day)", "5 sp", "2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Robes", "1 gp", "4 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Rope, hempen (50 feet)", "1 gp", "10 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Rope, silk (50 feet)", "10 gp", "5 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Sack", "1 cp", "1/2 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Scale, merchant's", "5 gp", "3 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Sealing wax", "5 sp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Shovel", "2 gp", "5 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Signal whistle", "5 cp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Signet ring", "5 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Soap", "2 cp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Spellbook", "50 gp", "3 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Spikes, iron (10)", "1 gp", "5 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Spyglass", "1,000 gp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Tent, two-person", "2 gp", "20 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Tinderbox", "5 sp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Torch", "1 cp", "1 lb."))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Vial", "1 gp", ""))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Waterskin", "2 sp", "5 lb. (full)"))
adventuringGear.append(AdventuringGear.AdventuringGear("", "Whetstone", "1 cp", "1 lb."))
