from MasterEquipment import Trinkets

trinketsList = []

trinketsList.append(Trinkets.Trinkets("","","","",""))
#__init__(self, inCategory, inCost, inWeight, inTrinkNum, inTrinkDesc):
trinketsList.append(Trinkets.Trinkets("Normal","","","01","A mummified goblin hand"))
trinketsList.append(Trinkets.Trinkets("Normal","","","02","A piece of crystal that faintly glows in the moonlight"))
trinketsList.append(Trinkets.Trinkets("Normal","","","03","A gold coin minted in an unknown land"))
trinketsList.append(Trinkets.Trinkets("Normal","","","04","A diary written in a language you don’t know"))
trinketsList.append(Trinkets.Trinkets("Normal","","","05","A brass ring that never tarnishes"))
trinketsList.append(Trinkets.Trinkets("Normal","","","06","An old chess piece made from glass"))
trinketsList.append(Trinkets.Trinkets("Normal","","","07","A pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips"))
trinketsList.append(Trinkets.Trinkets("Normal","","","08","A small idol depicting a nightmarish creature that gives you unsettling dreams when you sleep near it"))
trinketsList.append(Trinkets.Trinkets("Normal","","","09","A rope necklace from which dangles four mummified elf fingers"))
trinketsList.append(Trinkets.Trinkets("Normal","","","10","The deed for a parcel of land in a realm unknown to you"))
trinketsList.append(Trinkets.Trinkets("Normal","","","11","A 1-ounce block made from an unknown material"))
trinketsList.append(Trinkets.Trinkets("Normal","","","12","A small cloth doll skewered with needles"))
trinketsList.append(Trinkets.Trinkets("Normal","","","13","A tooth from an unknown beast opened"))
trinketsList.append(Trinkets.Trinkets("Normal","","","14","An enormous scale, perhaps from a dragon	"))
trinketsList.append(Trinkets.Trinkets("Normal","","","15","A bright green feather"))
trinketsList.append(Trinkets.Trinkets("Normal","","","16","An old divination card bearing your likeness"))
trinketsList.append(Trinkets.Trinkets("Normal","","","17","A glass orb filled with moving smoke"))
trinketsList.append(Trinkets.Trinkets("Normal","","","18","A 1-pound egg with a bright red shell"))
trinketsList.append(Trinkets.Trinkets("Normal","","","19","A pipe that blows bubbles"))
trinketsList.append(Trinkets.Trinkets("Normal","","","20","A glass jar containing a weird bit of flesh floating in pickling fluid"))
trinketsList.append(Trinkets.Trinkets("Normal","","","21","A tiny gnome-crafted music box that plays a song you dimly remember from your childhood"))
trinketsList.append(Trinkets.Trinkets("Normal","","","22","A small wooden statuette of a smug halfling	"))
trinketsList.append(Trinkets.Trinkets("Normal","","","23","A brass orb etched with strange runes"))
trinketsList.append(Trinkets.Trinkets("Normal","","","24","A multicolored stone disk"))
trinketsList.append(Trinkets.Trinkets("Normal","","","25","A tiny silver icon of a raven"))
trinketsList.append(Trinkets.Trinkets("Normal","","","26","A bag containing forty-seven humanoid teeth, one of which is rotten"))
trinketsList.append(Trinkets.Trinkets("Normal","","","27","A shard of obsidian that always feels warm to the touch"))
trinketsList.append(Trinkets.Trinkets("Normal","","","28","A dragon's bony talon hanging from a plain leather necklace"))
trinketsList.append(Trinkets.Trinkets("Normal","","","29","A pair of old socks"))
trinketsList.append(Trinkets.Trinkets("Normal","","","30","A blank book whose pages refuse to hold ink, chalk, graphite, or any other substance for marking"))
trinketsList.append(Trinkets.Trinkets("Normal","","","31","A silver badge in the shape of a five-pointed star"))
trinketsList.append(Trinkets.Trinkets("Normal","","","32","A knife that belonged to a relative"))
trinketsList.append(Trinkets.Trinkets("Normal","","","33","A glass vial filled with nail clippings"))
trinketsList.append(Trinkets.Trinkets("Normal","","","34","A rectangular metal device with two tiny metal cups on one end that throws sparks when wet"))
trinketsList.append(Trinkets.Trinkets("Normal","","","35","A white, sequined glove sized for a human"))
trinketsList.append(Trinkets.Trinkets("Normal","","","36","A vest with one hundred tiny pockets"))
trinketsList.append(Trinkets.Trinkets("Normal","","","37","A small, weightless stone block"))
trinketsList.append(Trinkets.Trinkets("Normal","","","38","A tiny sketch portrait of a goblin"))
trinketsList.append(Trinkets.Trinkets("Normal","","","39","An empty glass vial that smells of perfume when opened"))
trinketsList.append(Trinkets.Trinkets("Normal","","","40","A gemstone that looks like a lump of coal when examined by anyone but you"))
trinketsList.append(Trinkets.Trinkets("Normal","","","41","A scrap of cloth from an old banner"))
trinketsList.append(Trinkets.Trinkets("Normal","","","42","A rank insignia from a lost legionnaire"))
trinketsList.append(Trinkets.Trinkets("Normal","","","43","A tiny silver bell without a clapper"))
trinketsList.append(Trinkets.Trinkets("Normal","","","44","A mechanical canary inside a gnomish lamp"))
trinketsList.append(Trinkets.Trinkets("Normal","","","45","A tiny chest carved to look like it has numerous feet on the bottom"))
trinketsList.append(Trinkets.Trinkets("Normal","","","46","A dead sprite inside a clear glass bottle"))
trinketsList.append(Trinkets.Trinkets("Normal","","","47","A metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)"))
trinketsList.append(Trinkets.Trinkets("Normal","","","48","A glass orb filled with water, in which swims a clockwork goldfish"))
trinketsList.append(Trinkets.Trinkets("Normal","","","49","A silver spoon with an M engraved on the handle"))
trinketsList.append(Trinkets.Trinkets("Normal","","","50","A whistle made from gold-colored wood"))
trinketsList.append(Trinkets.Trinkets("Normal","","","51","A dead scarab beetle the size of your hand"))
trinketsList.append(Trinkets.Trinkets("Normal","","","52","Two toy soldiers, one with a missing head"))
trinketsList.append(Trinkets.Trinkets("Normal","","","53","A small box filled with different-sized buttons"))
trinketsList.append(Trinkets.Trinkets("Normal","","","54","A candle that can’t be lit"))
trinketsList.append(Trinkets.Trinkets("Normal","","","55","A tiny cage with no door"))
trinketsList.append(Trinkets.Trinkets("Normal","","","56","An old key"))
trinketsList.append(Trinkets.Trinkets("Normal","","","57","An indecipherable treasure map"))
trinketsList.append(Trinkets.Trinkets("Normal","","","58","A hilt from a broken sword"))
trinketsList.append(Trinkets.Trinkets("Normal","","","59","A rabbit’s foot"))
trinketsList.append(Trinkets.Trinkets("Normal","","","60","A glass eye"))
trinketsList.append(Trinkets.Trinkets("Normal","","","61","A cameo carved in the likeness of a hideous person"))
trinketsList.append(Trinkets.Trinkets("Normal","","","62","A silver skull the size of a coin"))
trinketsList.append(Trinkets.Trinkets("Normal","","","63","An alabaster mask"))
trinketsList.append(Trinkets.Trinkets("Normal","","","64","A pyramid of sticky black incense that smells very bad"))
trinketsList.append(Trinkets.Trinkets("Normal","","","65","A nightcap that, when worn, gives you pleasant dreams"))
trinketsList.append(Trinkets.Trinkets("Normal","","","66","A single caltrop made from bone"))
trinketsList.append(Trinkets.Trinkets("Normal","","","67","A gold monocle frame without the lens"))
trinketsList.append(Trinkets.Trinkets("Normal","","","68","A 1-inch cube, each side painted a different color"))
trinketsList.append(Trinkets.Trinkets("Normal","","","69","A crystal knob from a door"))
trinketsList.append(Trinkets.Trinkets("Normal","","","70","A small packet filled with pink dust"))
trinketsList.append(Trinkets.Trinkets("Normal","","","71","A fragment of a beautiful song, written as musical notes on two pieces of parchment"))
trinketsList.append(Trinkets.Trinkets("Normal","","","72","A silver teardrop earring made from a real teardrop"))
trinketsList.append(Trinkets.Trinkets("Normal","","","73","The shell of an egg painted with scenes of human misery in disturbing detail"))
trinketsList.append(Trinkets.Trinkets("Normal","","","74","A fan that, when unfolded, shows a sleeping cat"))
trinketsList.append(Trinkets.Trinkets("Normal","","","75","A set of bone pipes"))
trinketsList.append(Trinkets.Trinkets("Normal","","","76","A four-leaf clover pressed inside a book discussing manners and etiquette"))
trinketsList.append(Trinkets.Trinkets("Normal","","","77","A sheet of parchment upon which is drawn a complex mechanical contraption"))
trinketsList.append(Trinkets.Trinkets("Normal","","","78","An ornate scabbard that fits no blade you have found so far"))
trinketsList.append(Trinkets.Trinkets("Normal","","","79","An invitation to a party where a murder happened"))
trinketsList.append(Trinkets.Trinkets("Normal","","","80","A bronze pentacle with an etching of a rat's head in its center"))
trinketsList.append(Trinkets.Trinkets("Normal","","","81","A purple handkerchief embroidered with the name of a powerful archmage"))
trinketsList.append(Trinkets.Trinkets("Normal","","","82","Half of a floorplan for a temple, castle, or some other structure"))
trinketsList.append(Trinkets.Trinkets("Normal","","","83","A bit of folded cloth that, when unfolded, turns into a stylish cap"))
trinketsList.append(Trinkets.Trinkets("Normal","","","84","A receipt of deposit at a bank in a far-flung city"))
trinketsList.append(Trinkets.Trinkets("Normal","","","85","A diary with seven missing pages"))
trinketsList.append(Trinkets.Trinkets("Normal","","","86","An empty silver snuffbox bearing an inscription on the surface that says “dreams’’"))
trinketsList.append(Trinkets.Trinkets("Normal","","","87","An iron holy symbol devoted to an unknown god"))
trinketsList.append(Trinkets.Trinkets("Normal","","","88","A book that tells the story of a legendary hero's rise and fall, with the last chapter missing"))
trinketsList.append(Trinkets.Trinkets("Normal","","","89","A vial of dragon blood"))
trinketsList.append(Trinkets.Trinkets("Normal","","","90","An ancient arrow of elven design"))
trinketsList.append(Trinkets.Trinkets("Normal","","","91","A needle that never bends"))
trinketsList.append(Trinkets.Trinkets("Normal","","","92","An ornate brooch of dwarven design"))
trinketsList.append(Trinkets.Trinkets("Normal","","","93","An empty wine bottle bearing a pretty label that says, 'The Wizard of Wines Winery, Red Dragon Crush, 331422-W'"))
trinketsList.append(Trinkets.Trinkets("Normal","","","94","A mosaic tile with a multicolored, glazed surface"))
trinketsList.append(Trinkets.Trinkets("Normal","","","95","A petrified mouse"))
trinketsList.append(Trinkets.Trinkets("Normal","","","96","A black pirate flag adorned with a dragon's skull and crossbones"))
trinketsList.append(Trinkets.Trinkets("Normal","","","97","A tiny mechanical crab or spider that moves about when it’s not being observed"))
trinketsList.append(Trinkets.Trinkets("Normal","","","98","A glass jar containing lard with a label that reads, “Griffon Grease”"))
trinketsList.append(Trinkets.Trinkets("Normal","","","99","A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body"))
trinketsList.append(Trinkets.Trinkets("Normal","","","00","A metal urn containing the ashes of a hero"))


trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","01-02","A picture you drew as a child of your imaginary friend"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","03-04","A lock that opens when blood is dripped in its keyhole"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","05-06","Clothes stolen from a scarecrow"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","07-08","A spinning top carved with four faces: happy, sad, wrathful, and dead"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","09-10","The necklace of a sibling who died on the day you were born"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","11-12","A wig from someone executed by beheading"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","13-14","The unopened letter to you from your dying father"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","15-16","A pocket watch that runs backward for an hour every midnight"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","17-18","A winter coat stolen from a dying soldier"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","19-20","A bottle of invisible ink that can only be read at sunset"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","21-22","A wineskin that refills when interred with a dead person for a night"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","23-24","A set of silverware used by a king for his last meal"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","25-26","A spyglass that always shows the world suffering a terrible storm"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","27-28","A cameo with the profile’s face scratched away"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","29-30","A lantern with a black candle that never runs out and that burns with green flame"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","31-32","A teacup from a child’s tea set, stained with blood"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","33-34","A little black book that records your dreams, and yours alone, when you sleep"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","35-36","A necklace formed of the interlinked holy symbols of a dozen deities"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","37-38","A hangman’s noose that feels heavier than it should"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","39-40","A birdcage into which small birds fly but once inside never eat or leave"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","41-42","A lepidopterist’s box filled dead moths with skull-like patterns on their wings"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","43-44","A jar of pickled ghouls’ tongues"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","45-46","The wooden hand of a notorious pirate"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","47-48","A urn with the ashes of a dead relative"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","49-50","A hand mirror backed with a bronze depiction of a medusa"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","51-52","Pallid leather gloves crafted with ivory fingernails"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","53-54","Dice made from the knuckles of a notorious charlatan"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","55-56","A ring of keys for forgotten locks"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","57-58","Nails from the coffin of a murderer"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","59-60","A key to the family crypt"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","61-62","A bouquet of funerary flowers that always looks and smells fresh"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","63-64","A switch used to discipline you as a child"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","65-66","A music box that plays by itself whenever someone holding it dances"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","67-68","A walking cane with an iron ferule that strikes sparks on stone"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","69-70","A flag from a ship lost at sea"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","71-72","Porcelain doll’s head that always seems to be looking at you"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","73-74","A wolf’s head wrought in silver that is also a whistle."))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","75-76","A small mirror that shows a much older version of the viewer"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","77-78","Small, worn book of children’s nursery rhymes."))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","79-80","A mummified raven claw"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","81-82","A broken pendent of a silver dragon that’s always cold to the touch"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","83-84","A small locked box that quietly hums a lovely melody at night but you always forget it in the morning"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","85-86","An inkwell that makes one a little nauseous when staring at it"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","87-88","An old little doll made from a dark, dense wood and missing a hand and a foot"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","89-90","A black executioner’s hood"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","91-92","A pouch made of flesh, with a sinew drawstring"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","93-94","A tiny spool of black thread that never runs out"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","95-96","A tiny clockwork figurine of a dancer that’s missing a gear and doesn’t work"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","97-98","A black wooden pipe that creates puffs of smoke that look like skulls"))
trinketsList.append(Trinkets.Trinkets("Gothic Trinkets","","","99-00","A vial of perfume, the scent of which only certain creatures can detect"))



for x in trinketsList:
    print(x.toString())
